In [24]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score ,recall_score, f1_score,  classification_report
from sklearn.model_selection import train_test_split

import pandas as pd
import numpy as np

In [22]:
df = pd.read_csv('../AI_PBL_data/web_server_logs_2.csv')
df

                 ip            timestamp   method  status_code  size  label
0     192.168.1.138  2024-11-30 09:26:01  OPTIONS          301   541      0
1     192.168.1.130  2024-11-30 12:00:34  OPTIONS          200  5239      0
2      192.168.1.75  2024-12-01 00:22:12     POST          200  5778      0
3     192.168.1.176  2024-11-30 19:33:26   DELETE          200  3911      0
4        10.0.0.113  2024-11-30 05:37:26      GET          200  7765      0
...             ...                  ...      ...          ...   ...    ...
1495   192.168.1.65  2024-11-30 05:06:59      GET          503   962      1
1496   192.168.1.51  2024-11-30 17:12:08  OPTIONS          200  6500      0
1497     10.0.0.116  2024-11-30 21:50:56  OPTIONS          200  3854      0
1498    192.168.1.2  2024-11-30 08:23:04      GET          404  4338      1
1499       10.0.0.1  2024-11-30 21:23:58   DELETE          503  9037      1

[1500 rows x 6 columns]

In [23]:
df['timestamp'] = pd.to_datetime(df['timestamp'])
df['hour'] = df['timestamp'].dt.hour
df.info()

df['is_error'] = df['status_code'].apply(lambda x : 1 if x >= 400 else 0)
df['label'] = df['is_error']
 
df = pd.get_dummies(df, columns=['method'])

df['size_log'] = np.log1p(df['size'])
# result_df = pd.concat([df, df_encoded], axis=1)

# result_df
# df['hour']

df

<class 'pandas.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ip           1500 non-null   str
 1   timestamp    1500 non-null   datetime64[us]
 2   method       1500 non-null   str
 3   status_code  1500 non-null   int64
 4   size         1500 non-null   int64
 5   label        1500 non-null   int64
 6   hour         1500 non-null   int32
dtypes: datetime64[us](1), int32(1), int64(3), str(2)
memory usage: 76.3 KB

,ip,timestamp,status_code,size,label,hour,is_error,method_DELETE,method_GET,method_OPTIONS,method_POST,method_PUT,size_log
0,192.168.1.138,2024-11-30 09:26:01,301,541,0,9,0,False,False,True,False,False,6.295266
1,192.168.1.130,2024-11-30 12:00:34,200,5239,0,12,0,False,False,True,False,False,8.564077
2,192.168.1.75,2024-12-01 00:22:12,200,5778,0,0,0,False,False,False,True,False,8.661986
3,192.168.1.176,2024-11-30 19:33:26,200,3911,0,19,0,True,False,False,False,False,8.271804
4,10.0.0.113,2024-11-30 05:37:26,200,7765,0,5,0,False,True,False,False,False,8.957511
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,192.168.1.65,2024-11-30 05:06:59,503,962,1,5,1,False,True,False,False,False,6.870053
1496,192.168.1.51,2024-11-30 17:12:08,200,6500,0,17,0,False,False,True,False,False,8.779711
1497,10.0.0.116,2024-11-30 21:50:56,200,3854,0,21,0,False,False,True,False,False,8.257126
1498,192.168.1.2,2024-11-30 08:23:04,404,4338,1,8,1,False,True,False,False,False,8.375399
1499,10.0.0.1,2024-11-30 21:23:58,503,9037,1,21,1,True,False,False,False,False,9.109193

In [ ]:
X = df.drop(columns='label')
y = df['label']

model = LogisticRegression()